import React, { useState, useEffect } from 'react';
import { documentApi } from '../../api/documentApi';
import DataTable from '../../components/common/DataTable';
import StatusBadge from '../../components/common/StatusBadge';
import { useToast } from '../../context/ToastContext';
import { FileCheck, Download } from 'lucide-react';

export default function DocumentCenter() {
  const [documents, setDocuments] = useState([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const { showToast } = useToast();

  useEffect(() => {
    const fetchDocs = async () => {
      setLoading(true);
      try {
        const res = await documentApi.getDocuments({ page, limit: 10, search });
        if (res.success) {
          setDocuments(res.data);
          setTotal(res.meta?.total || res.data.length);
        }
      } catch (err) {
        showToast(err.message || 'Failed to fetch document history', 'error');
      } finally {
        setLoading(false);
      }
    };
    fetchDocs();
  }, [page, search]);

  const columns = [
    { header: 'Document Type', accessor: 'docType', cell: (row) => <span className="font-bold text-slate-900">{row.docType}</span> },
    { header: 'Invoice #', accessor: 'invoiceNumber', cell: (row) => <span className="font-mono">{row.invoiceNumber}</span> },
    { header: 'Version', accessor: 'version', cell: (row) => <span className="px-2 py-0.5 bg-indigo-50 text-indigo-700 font-bold rounded text-[11px]">v{row.version}</span> },
    { header: 'Generated File', accessor: 'fileName', cell: (row) => <span className="text-slate-600 font-mono text-[11px]">{row.fileName}</span> },
    { header: 'Generated By', accessor: 'generatedBy', cell: (row) => row.generatedBy?.fullName },
    { header: 'Generated Date', accessor: 'createdAt', cell: (row) => new Date(row.createdAt).toLocaleString() },
    {
      header: 'Action',
      cell: (row) => (
        <a
          href={row.filePath}
          target="_blank"
          rel="noreferrer"
          className="flex items-center gap-1 px-3 py-1 bg-slate-900 text-white rounded-lg text-xs font-semibold hover:bg-slate-800 transition"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Download</span>
        </a>
      ),
    },
  ];

  return (
    <div className="p-8 space-y-6">
      <DataTable
        title="Export Document Archive & Version History"
        columns={columns}
        data={documents}
        total={total}
        page={page}
        onPageChange={setPage}
        onSearch={setSearch}
        loading={loading}
        exportFilename="document_archive_export"
      />
    </div>
  );
}
